### ISSUE TITLE
configure the new api for server and client （Java）

### ISSUE THREAD

**Issue by 3thinkthendoit** [rojanu/thrift-swift-finagle-example#1]
how to do it, I want to configure the tracer,timeout ,etc.....

**Comment by rojanu** [comment]
Could you be more specific,  I don't understand what are you trying to do?

**Comment by 3thinkthendoit** [comment]
my java code is（finagle old api） : 

 Server server = ServerBuilder.safeBuild(
                    service,
                    ServerBuilder.get().codec(new ThriftServerFramedCodec(conf, new TBinaryProtocol.Factory()))
                            .name(serviceName).maxConcurrentRequests(20).keepAlive(true)
                            .hostConnectionMaxIdleTime(Duration.fromMilliseconds(10000))
                            .readTimeout(Duration.fromMilliseconds(15000))
                            .tracer(ZipkinTracer.mk("192.168.115.105", 1463,sr,1))
                            .requestTimeout(Duration.fromMilliseconds(15000))
                            .bindTo(endpoint));
now  i want to konw how to configure hostConnectionMaxIdleTime,readTimeout and tracer requestTimeout  int the new API like this:

 Hello.ServiceIface impl = new HelloImpl();//服务端逻辑
          String strIface  = Hello.ServiceIface.class.getName();
          String processName = strIface.substring(0, strIface.indexOf("$ServiceIface"));
          Class<?> Processor = Class.forName(processName + "$Service");
          Class<?> p1 = Class.forName(processName + "$ServiceIface"); 
          Class<?> p2 = Class.forName(TProtocolFactory.class.getName()); 
          Constructor<?> con = Processor.getConstructor(p1, p2);
          TBinaryProtocol.Factory  protocolFactory = new TBinaryProtocol.Factory();
          Service<byte[], byte[]> service = (Service<byte[], byte[]>) con.newInstance(impl, protocolFactory);
          //不知道怎么配置 zipkin 超时时间 最大连接数等.....
          ListeningServer server = Thrift.serveIface("localhost:8080", impl);
          server.announce("zk!192.168.115.105:2181!/foo/test!1");
          Await.ready(server);

thank you very much.....

**Comment by rojanu** [comment]
Timeout on server has been removed, I remember reading on a Finagle doc that the future was being misused and therefore removed.

This might help: https://twitter.github.io/finagle/guide/Clients.html?highlight=timeout

You will be better of asking your questions on 
https://groups.google.com/forum/#!forum/finaglers
